import ingredientType from "../utils/type";

export const GET_API_INGREDIENTS_START = "GET_API_INGREDIENTS_START";
export const GET_API_INGREDIENTS_SUCCESS = "GET_API_INGREDIENTS_SUCCESS";
export const GET_API_INGREDIENTS_FAILED = "GET_API_INGREDIENTS_FAILED";
export const ADD_INGREDIENT_TO_ORDER = "ADD_INGREDIENT_TO_ORDER";
export const REMOVE_INGREDIENT_FROM_ORDER = "REMOVE_INGREDIENT_FROM_ORDER";
export const OPEN_INGREDIENT_DETAILS = "OPEN_INGREDIENT_DETAILS";
export const CLOSE_INGREDIENT_DETAILS = "CLOSE_INGREDIENT_DETAILS";

export const ADD_INGREDIENT = "ADD_INGREDIENT";
export interface actionAddIngredient {
  type: "ADD_INGREDIENT";
  ingredient: ingredientType;
}
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export interface actionRemoveIngredient {
  type: "REMOVE_INGREDIENT";
  ingredient: ingredientType;
}
export const MOVE_INGREDIENT = "MOVE_INGREDIENT";
export interface actionMoveIngredient {
    type: "MOVE_INGREDIENT";
    lastPositionId: number;
    newPositionId : number;
  }
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED = "POST_ORDER_FAILED";
export const OPEN_ORDER_MODAL = "OPEN_ORDER_MODAL";
export const CLOSE_ORDER_MODAL = "CLOSE_ORDER_MODAL";
export const ACTIVATE_TAB = "ACTIVATE_TAB";
export const POST_FORGOT_PASSWORD_SUCCESS = "POST_FORGOT_PASSWORD_SUCCESS";
export const POST_FORGOT_PASSWORD_FAILED = "POST_FORGOT_PASSWORD_FAILED";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILED = "POST_REGISTER_FAILED";
export const POST_RESET_PASSWORD_SUCCESS = "POST_RESET_PASSWORD_SUCCESS";
export const POST_RESET_PASSWORD_FAILED = "POST_RESET_PASSWORD_FAILED";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";
export const POST_TOKEN_SUCCESS = "POST_TOKEN_SUCCESS";
export const POST_TOKEN_FAILED = "POST_TOKEN_FAILED";
export const POST_LOGOUT_SUCCESS = "POST_LOGOUT_SUCCESS";
export const POST_LOGOUT_FAILED = "POST_LOGOUT_FAILED";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILED = "GET_USER_INFO_FAILED";
export const POST_STARTED = "POST_STARTED";
