export const BASE_URL = "https://norma.nomoreparties.space/api"
export const API_URL_INGREDIENTS = BASE_URL + "/ingredients";
export const API_URL_ORDERS = BASE_URL + "/orders";
export const API_URL_FORGOT_PASSWORD = BASE_URL + "/password-reset";
export const API_URL_RESET_PASSWORD = BASE_URL + "/password-reset/reset"
export const API_URL_REGISTER = BASE_URL + "/auth/register";
export const API_URL_LOGIN = BASE_URL + "/auth/login";
export const API_URL_LOGOUT = BASE_URL + "/auth/logout";
export const API_URL_TOKEN = BASE_URL + "/auth/token";
export const API_URL_GET_USER = BASE_URL + "/auth/user";
export const TOP_BOTTOM_TYPE = "bun";
export const ACCESS_TOKEN_LIFETIME = 20;